Silence compiler warnings about host device destructor (#4960)
We are seeing spurious compiler warnings like

> error: calling a __host__ function("std::vector<...> ::~vector()") from a __host__ __device__ function("cugraph::edge_property_view_t<...> ::~edge_property_view_t") is not allowed

This is clearly a compiler bug that has been fixed but affects 12.5 which is what runs in CI

Example [here](https://github.com/NVIDIA/cccl/actions/runs/13720179287/job/38373997200?pr=3953#step:6:12629)

Authors:
  - Michael Schellenberger Costa (https://github.com/miscco)
  - Seunghwa Kang (https://github.com/seunghwak)

Approvers:
  - Chuck Hastings (https://github.com/ChuckHastings)

URL: https://github.com/rapidsai/cugraph/pull/4960