Fix MG tests bugs (#2819)
A 22.10 PR leveraging the datasets API broke the MG `batch_betweenness_centrality` and `batch_edge_betweenness_centrality`. In fact, both tests are calling their non batch SG counterparts tests but with non datasets API objects leading to `AttributeError: 'str' object has no attribute 'get_graph'`. Another 22.10 PR which repartitioned  the dask dataframe also broke the above tests including the MG replication tests. In fact, those algos/function with `batch_enable=True` expect only one [partition](https://github.com/rapidsai/cugraph/blob/branch-22.12/python/cugraph/cugraph/dask/structure/replication.pyx#L38) which will later be replicated across all workers during the replication call. 

This PR fixes the above issues by not repartitioning the dask dataframe when `batch_enable=True` and also leverages the datasets API for MG `batch_betweenness_centrality` and `batch_edge_betweenness_centrality`

closes #2815

Authors:
  - Joseph Nke (https://github.com/jnke2016)

Approvers:
  - Rick Ratzel (https://github.com/rlratzel)

URL: https://github.com/rapidsai/cugraph/pull/2819