Include a thrust header that was missing to use thrust::max
cpp/tests/utilities/check_utilities.hpp: In member function ‘bool cugraph::test::device_nearly_equal<type_t>::operator()(type_t, type_t) const’:
cpp/tests/utilities/check_utilities.hpp:98:20: error: ‘max’ is not a member of ‘thrust’
98 | thrust::max(thrust::max(lhs, rhs) * threshold_ratio, threshold_magnitude);
| ^~~