Silence compiler warnings about host device destructor
We are seeing spurious compiler warnings like

error: calling a __host__ function("std::vector<...> ::~vector()") from a __host__ __device__ function("cugraph::edge_property_view_t<...> ::~edge_property_view_t") is not allowed

This is clearly a compiler bug that has been fixed but affects 12.5 which is what runs in CI