wheels CI: update to torch 2.10 for 'oldest' configuration (#5485)
Nightly wheel tests on the "oldest" configuration started failing
yesterday, like this:

```text
Collecting torch
  Downloading https://download-r2.pytorch.org/whl/cu129/torch-2.9.0%2Bcu129-cp311-cp311-manylinux_2_28_x86_64.whl.metadata (30 kB)
ERROR: THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
    torch from https://download-r2.pytorch.org/whl/cu129/torch-2.9.0%2Bcu129-cp311-cp311-manylinux_2_28_x86_64.whl#sha256=78005065547658b8c3fd2dd4d68f34625b0543494c947001b5303d253b22da5f:
        Expected sha256 05df84ccec407908cb70f89d6c2675b8220661f23d7de0cf899f4401f8ab2798
             Got        2b0a3a5d37a8d7447e56e7e4e27280f881e805fbae79130fa8874bcfe6eae333
```

([build
link](https://github.com/rapidsai/cugraph/actions/runs/24123257906/job/70425339392#step:13:150))

This looks like an issue with the metadata on `torch`'s index:
https://github.com/pytorch/pytorch/issues/145501#issuecomment-4207316144

For now, this proposes just testing against `torch-2.10.0` for the
"oldest" configuration, to get CI working again.

## Notes for Reviewers

### How I tested this

On an earlier commit, ran the full nightly matrix on `release/26.04`.
Saw it pass:
https://github.com/rapidsai/cugraph/actions/runs/24143566958/job/70480989274

This change isn't RAPIDS-branch-specific, so I'm confident this will
resolve this issue in the nightlies.