Added  #include <cuda/std/cmath> for correct cuda::std::log reference (#5039)
1. Added  #include <cuda/std/cmath> for correct cuda::std::log reference in sample_and_compute_local_nbr_indices.cuh
Without proper include, the following error would be raised during building libcugraph in my environment:

```
cpp/src/prims/detail/sample_and_compute_local_nbr_indices.cuh([[1994|2006|2260|2272]]):
error: namespace "cuda::std" has no member "log"
	return cuda::std::min(-cuda::std::log(r) / b, std::numeric_limits<bias_t>::max());
```
2. Update od_shortest_distances_impl.cuh, fix missing required parameter: invalid_distance in struct e_op_t
Without proper include, the following error would be raised during building libcugraph in my environment:

```
cpp/src/traversal/od_shortest_distances_impl.cuh(143):
	Build log is lost, but the line 143 would complain on missing variable invalid_distance.
```


> Apologies for missing the labels earlier, and now I'm not able to edit them myself. Could someone with the appropriate permissions kindly add the 'bug' and 'non-breaking' labels? Thanks for your help!

Authors:
  - SagaFish (https://github.com/SagaciousFish)

Approvers:
  - Chuck Hastings (https://github.com/ChuckHastings)

URL: https://github.com/rapidsai/cugraph/pull/5039